# Generated by Django 2.1 on 2019-04-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='male', max_length=7),
        ),
        migrations.AddField(
            model_name='person',
            name='major',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('freshman', 'freshman'), ('junior', 'junior'), ('sophomore', 'sophomore'), ('senior', 'senior'), ('graduate', 'graduate')], default='freshman', max_length=20),
        ),
    ]
