# Generated by Django 2.1 on 2019-04-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190413_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=196)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('freshman', 'freshman'), ('senior', 'senior'), ('sophomore', 'sophomore'), ('junior', 'junior'), ('graduate', 'graduate')], default='freshman', max_length=20),
        ),
    ]
