# Generated by Django 2.1.1 on 2019-04-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190413_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('graduate', 'graduate'), ('sophomore', 'sophomore'), ('junior', 'junior'), ('senior', 'senior'), ('freshman', 'freshman')], default='freshman', max_length=20),
        ),
    ]
