# Generated by Django 2.1.1 on 2019-04-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20190414_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedcode', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('freshman', 'freshman'), ('junior', 'junior'), ('sophomore', 'sophomore'), ('senior', 'senior'), ('graduate', 'graduate')], default='freshman', max_length=20),
        ),
    ]
