# Generated by Django 2.1.1 on 2019-04-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20190414_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('graduate', 'graduate'), ('senior', 'senior'), ('sophomore', 'sophomore'), ('junior', 'junior'), ('freshman', 'freshman')], default='freshman', max_length=20),
        ),
    ]
