# Generated by Django 2.1.1 on 2019-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20190414_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('freshman', 'freshman'), ('junior', 'junior'), ('sophomore', 'sophomore'), ('graduate', 'graduate'), ('senior', 'senior')], default='freshman', max_length=20),
        ),
    ]
