# Generated by Django 2.1.1 on 2019-04-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20190414_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(default='', upload_to='')),
                ('name', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('graduate', 'graduate'), ('junior', 'junior'), ('freshman', 'freshman'), ('sophomore', 'sophomore'), ('senior', 'senior')], default='freshman', max_length=20),
        ),
    ]
