# Generated by Django 2.1.1 on 2019-04-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20190415_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('junior', 'junior'), ('graduate', 'graduate'), ('sophomore', 'sophomore'), ('senior', 'senior'), ('freshman', 'freshman')], default='freshman', max_length=20),
        ),
    ]
