# Generated by Django 2.1.1 on 2019-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20190415_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='male', max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('graduate', 'graduate'), ('sophomore', 'sophomore'), ('junior', 'junior'), ('senior', 'senior'), ('freshman', 'freshman')], default='freshman', max_length=20),
        ),
    ]
