# Generated by Django 2.1.1 on 2019-04-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20190415_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('senior', 'senior'), ('freshman', 'freshman'), ('graduate', 'graduate'), ('junior', 'junior'), ('sophomore', 'sophomore')], default='freshman', max_length=20),
        ),
    ]
