# Generated by Django 2.1.1 on 2019-04-18 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20190418_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='uploaded_by',
            field=models.TextField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('senior', 'senior'), ('sophomore', 'sophomore'), ('freshman', 'freshman'), ('junior', 'junior'), ('graduate', 'graduate')], default='freshman', max_length=20),
        ),
    ]
