# Generated by Django 2.1.1 on 2019-04-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20190418_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='memory',
            name='uploaded_by',
            field=models.TextField(default='random guy', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='male', max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('sophomore', 'sophomore'), ('senior', 'senior'), ('graduate', 'graduate'), ('junior', 'junior'), ('freshman', 'freshman')], default='freshman', max_length=20),
        ),
    ]
