# Generated by Django 2.1.1 on 2019-04-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20190418_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('sophomore', 'sophomore'), ('graduate', 'graduate'), ('freshman', 'freshman'), ('senior', 'senior'), ('junior', 'junior')], default='', max_length=20),
        ),
    ]
