# Generated by Django 2.1.1 on 2019-04-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20190418_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('junior', 'junior'), ('senior', 'senior'), ('sophomore', 'sophomore'), ('graduate', 'graduate'), ('freshman', 'freshman')], default='', max_length=20),
        ),
    ]
