# Generated by Django 2.1.1 on 2019-04-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_auto_20190418_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('freshman', 'freshman'), ('senior', 'senior'), ('graduate', 'graduate'), ('sophomore', 'sophomore'), ('junior', 'junior')], default='', max_length=20),
        ),
    ]
